name: Build KPF & Pongo

on:
  # Manual trigger only
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update repository
        run: |
          git submodule update --init --recursive
          git fetch --all
          git reset --hard origin/$(git branch --show-current)
          git submodule update --recursive --remote

      - name: Compile KPF and Pongo
        run: |
          make

      - name: Prepare upload directory
        run: |
          mkdir upload
          mv build/Pongo.bin upload/
          mv build/checkra1n-kpf-pongo upload/

      - name: Compile KPF and Pongo Development
        run: |
          make clean
          make DEV_BUILD=1

      - name: Prepare upload directory Development
        run: |
          mv build/Pongo.bin upload/Pongo.bin.development
          mv build/checkra1n-kpf-pongo upload/checkra1n-kpf-pongo.development

      - name: Upload artifacts (attached to run)
        uses: actions/upload-artifact@v4
        with:
          name: kpf-pongo-${{ github.ref_name }}
          path: upload
          if-no-files-found: error
          retention-days: 30

